name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Install Railway
        run: npm install -g @railway/cli

      - name: Deploy
        run: railway up dist
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
